FROM python:3.11

RUN apt-get update \
    && apt-get install -y gcc libpq-dev \
    && apt-get clean

COPY ./req.txt /backend/requirements.txt
RUN pip install -r /backend/requirements.txt

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY ./skrollik /backend
WORKDIR /backend